version: 2.1
jobs:
  validate:
    docker:
      - image: gcr.io/windmill-public-containers/tilt-extensions-ci@sha256:521e0697acc3dde27cb39d3052dfe5434c083fc99e1ffa0119853a7de0090715

    steps:
      - checkout
      - run: GOBIN=$HOME/.bin go get github.com/tilt-dev/tilt-extensions-ci && go install 'github.com/tilt-dev/tilt-extensions-ci@v1.1.0'
      - run: $HOME/.bin/tilt-extensions-ci .

  shellcheck:
    docker:
      - image: gcr.io/windmill-public-containers/tilt-extensions-ci@sha256:521e0697acc3dde27cb39d3052dfe5434c083fc99e1ffa0119853a7de0090715

    steps:
      - checkout
      - run: make shellcheck

  test:
    docker:
      - image: gcr.io/windmill-public-containers/tilt-extensions-ci@sha256:521e0697acc3dde27cb39d3052dfe5434c083fc99e1ffa0119853a7de0090715

    steps:
      - setup_remote_docker:
          version: '20.10.6'
      - checkout
      - run: ctlptl create cluster kind --registry=ctlptl-registry && timeout -v -k 60s 20m ./test.sh

workflows:
  version: 2
  build:
    jobs:
      - validate
      - shellcheck
      - test
